name: Trigger auto deployment for rcbinator-web-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rcbinator-web-app-AutoDeployTrigger-a7a6a969-47cd-4291-b976-40a0a48c2616.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RCBINATORWEBAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RCBINATORWEBAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RCBINATORWEBAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}01-docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: devopsorkshop.azurecr.io
          registryUsername: ${{ secrets.RCBINATORWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RCBINATORWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: rcbinator-web-app
          resourceGroup: just-for-hacks
          imageToBuild: devopsorkshop.azurecr.io/rcbinator-web-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


