name: Trigger auto deployment for rcbinator-web-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/rcbinator-web-app-AutoDeployTrigger-e7ee2b21-4c8b-4df9-ae81-0a66b5c117c8.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RCBINATORWEBAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}01-docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: devopsorkshop.azurecr.io
          registryUsername: ${{ secrets.RCBINATORWEBAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RCBINATORWEBAPP_REGISTRY_PASSWORD }}
          containerAppName: rcbinator-web-app
          resourceGroup: just-for-hacks
          imageToBuild: devopsorkshop.azurecr.io/rcbinator-web-app:${{ github.sha }}
          
            

     

